/**
 * Builds the Supabase auth mail templates in every app language
 * (docs/mail-templates/, docs/i18n.md area 6b). Supabase has one template
 * per mail; each file here picks the text by the account's language
 * (`.Data.locale`, set by the app at sign-up and when the language changes)
 * and falls back to English. Paste them in the Supabase dashboard:
 * Authentication → Emails → Templates. `--check` fails when a file is out of
 * date (`npm run check:i18n`).
 */

import fs from 'node:fs';
import path from 'node:path';

import { LOCALES } from '../src/shared/i18n/locales';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const messagesDir = path.join(root, 'src/shared/i18n/messages');
const outDir = path.join(root, 'docs/mail-templates');

const MAILS = [
  { file: 'confirm-signup', key: 'mail.confirm' },
  { file: 'reset-password', key: 'mail.reset' },
  { file: 'change-email', key: 'mail.change' },
] as const;

/** `{email}` in a text becomes the template variable. */
const GO_VARIABLES: Record<string, string> = { email: '{{ .Email }}', newEmail: '{{ .NewEmail }}' };

const catalogs = Object.fromEntries(
  LOCALES.map(({ code }) => [code, JSON.parse(fs.readFileSync(path.join(messagesDir, `${code}.json`), 'utf8')) as Record<string, string>]),
);
const english = catalogs.en;

function escapeHtml(text: string) {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function text(code: string, key: string) {
  const value = catalogs[code]?.[key] ?? english[key];
  if (value === undefined) throw new Error(`${key} is missing in en.json`);
  return escapeHtml(value).replace(/\{(\w+)\}/g, (match, name: string) => GO_VARIABLES[name] ?? match);
}

function body(code: string, key: string) {
  return [
    `<h2>${text(code, `${key}.heading`)}</h2>`,
    `<p>${text(code, `${key}.text`)}</p>`,
    `<p><a href="{{ .ConfirmationURL }}">${text(code, `${key}.button`)}</a></p>`,
    `<p>${text(code, 'mail.ignore')}</p>`,
  ].join('\n');
}

/** English last, as the fallback for every other or unknown language. */
function byLanguage(render: (code: string) => string) {
  const others = LOCALES.map(({ code }) => code).filter((code) => code !== 'en');
  if (others.length === 0) return render('en');
  return [
    ...others.map((code, index) => `{{ ${index === 0 ? 'if' : 'else if'} eq .Data.locale "${code}" }}\n${render(code)}`),
    `{{ else }}\n${render('en')}\n{{ end }}`,
  ].join('\n');
}

const files: Record<string, string> = {};
for (const mail of MAILS) {
  files[`${mail.file}.html`] = `<!-- Generated by \`npm run mail-templates\` from the app texts (${mail.key}.*). Paste into Supabase → Authentication → Emails. -->\n${byLanguage((code) => body(code, mail.key))}\n`;
  files[`${mail.file}.subject.txt`] = `${byLanguage((code) => text(code, `${mail.key}.subject`)).replace(/\n/g, '')}\n`;
}

if (process.argv.includes('--check')) {
  const stale = Object.entries(files).filter(([name, content]) => {
    const full = path.join(outDir, name);
    return !fs.existsSync(full) || fs.readFileSync(full, 'utf8') !== content;
  });
  if (stale.length > 0) {
    console.log(`FAIL  docs/mail-templates is out of date (${stale.map(([name]) => name).join(', ')}): run \`npm run mail-templates\` and paste the changed templates into Supabase.`);
    process.exit(1);
  }
  console.log('mail templates up to date');
} else {
  fs.mkdirSync(outDir, { recursive: true });
  for (const [name, content] of Object.entries(files)) fs.writeFileSync(path.join(outDir, name), content);
  console.log(`wrote ${Object.keys(files).length} files to docs/mail-templates`);
}
